df_graph2 %>% ggplot(aes(x=ALL1011PREV, y=ADDITIONALRISKOFCOMPLICATION, color=ADDITIONALRISKOFSTROKE)) + geom_point()
df_graph2 %>% ggplot(aes(x=TYPE11011PREV, y=ADDITIONALRISKOFCOMPLICATION, color=ADDITIONALRISKOFSTROKE)) + geom_point()
df_graph2 %>% ggplot(aes(x=TYPE21011PREV, y=ADDITIONALRISKOFCOMPLICATION, color=ADDITIONALRISKOFSTROKE)) + geom_point()
